
import __ASTRO_IMAGE_IMPORT_1RTwrx from "./images/post-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FBoosting+Sales+with+Effective+Search+Engine+Optimization+%28SEO%29.mdx";
import __ASTRO_IMAGE_IMPORT_5ofGf from "./images/post-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FGrowing+Your+New+YouTube+Channel+with+Effective+SEO+Strategies.mdx";
import __ASTRO_IMAGE_IMPORT_Z2okV68 from "./images/post-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FLeveraging+Google+Ads+for+Increased+Business+Sales.mdx";
import __ASTRO_IMAGE_IMPORT_1oJB3c from "./images/post-6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FStrategies+to+Boost+Sales+Through+Your+Website.mdx";
import __ASTRO_IMAGE_IMPORT_2iIF28 from "./images/post-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FMaximizing+Business+Growth+Through.mdx";
import __ASTRO_IMAGE_IMPORT_2ds1cb from "./images/post-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FLeveraging+Social+Media+Marketing+for+Business+Growth.mdx";
import __ASTRO_IMAGE_IMPORT_Z21iNUg from "./images/post-7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUsing+SEO+Strategies+for+Business+Growth.mdx";
import __ASTRO_IMAGE_IMPORT_Z7PRQ5 from "./images/post-8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUtilizing+YouTube+for+Business+Growth.mdx";
export default new Map([["./images/post-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FBoosting+Sales+with+Effective+Search+Engine+Optimization+%28SEO%29.mdx", __ASTRO_IMAGE_IMPORT_1RTwrx], ["./images/post-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FGrowing+Your+New+YouTube+Channel+with+Effective+SEO+Strategies.mdx", __ASTRO_IMAGE_IMPORT_5ofGf], ["./images/post-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FLeveraging+Google+Ads+for+Increased+Business+Sales.mdx", __ASTRO_IMAGE_IMPORT_Z2okV68], ["./images/post-6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FStrategies+to+Boost+Sales+Through+Your+Website.mdx", __ASTRO_IMAGE_IMPORT_1oJB3c], ["./images/post-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FMaximizing+Business+Growth+Through.mdx", __ASTRO_IMAGE_IMPORT_2iIF28], ["./images/post-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FLeveraging+Social+Media+Marketing+for+Business+Growth.mdx", __ASTRO_IMAGE_IMPORT_2ds1cb], ["./images/post-7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUsing+SEO+Strategies+for+Business+Growth.mdx", __ASTRO_IMAGE_IMPORT_Z21iNUg], ["./images/post-8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FUtilizing+YouTube+for+Business+Growth.mdx", __ASTRO_IMAGE_IMPORT_Z7PRQ5]]);
		