
export default new Map([
["src/content/posts/Boosting Sales with Effective Search Engine Optimization (SEO).mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FBoosting+Sales+with+Effective+Search+Engine+Optimization+%28SEO%29.mdx&astroContentModuleFlag=true")],
["src/content/posts/Growing Your New YouTube Channel with Effective SEO Strategies.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FGrowing+Your+New+YouTube+Channel+with+Effective+SEO+Strategies.mdx&astroContentModuleFlag=true")],
["src/content/posts/Leveraging Google Ads for Increased Business Sales.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FLeveraging+Google+Ads+for+Increased+Business+Sales.mdx&astroContentModuleFlag=true")],
["src/content/posts/Strategies to Boost Sales Through Your Website.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FStrategies+to+Boost+Sales+Through+Your+Website.mdx&astroContentModuleFlag=true")],
["src/content/posts/Using SEO Strategies for Business Growth.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FUsing+SEO+Strategies+for+Business+Growth.mdx&astroContentModuleFlag=true")],
["src/content/posts/Maximizing Business Growth Through.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FMaximizing+Business+Growth+Through.mdx&astroContentModuleFlag=true")],
["src/content/posts/Utilizing YouTube for Business Growth.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FUtilizing+YouTube+for+Business+Growth.mdx&astroContentModuleFlag=true")],
["src/content/posts/Leveraging Social Media Marketing for Business Growth.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2FLeveraging+Social+Media+Marketing+for+Business+Growth.mdx&astroContentModuleFlag=true")]]);
		