import { glob } from 'astro/loaders';
import { defineCollection, z } from "astro:content";

// This file is auto-generated by the 'generate-collections.mjs' script. Do not edit manually.
// Generated on: 2025-07-13T22:46:08.111Z

// A generic base schema that allows for common fields and any other fields.
// This provides flexibility while ensuring core fields like 'title' are present.
const baseSchema = z.object({
  title: z.string(),
  // Make everything optional and more flexible
  aliases: z.union([z.array(z.string()), z.string()]).optional(),
  tags: z.union([z.array(z.string()), z.string()]).optional(),
  collection: z.string().optional(),
  kind: z.string().optional(),
}).passthrough(); // Allow any additional fields// .passthrough() allows any other fields without validation.


// Collection for: abilities
const abilities = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/abilities',
  })
});
// Collection for: artifacts
const artifacts = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/artifacts',
  })
});
// Collection for: cantrips
const cantrips = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/cantrips',
  })
});
// Collection for: character-arcs
const characterarcs = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/character-arcs',
  })
});
// Collection for: character-options
const characteroptions = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/character-options',
  })
});
// Collection for: creatures-npcs
const creaturesnpcs = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/creatures-npcs',
  })
});
// Collection for: cypher-shorts-scenarios
const cyphershortsscenarios = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/cypher-shorts-scenarios',
  })
});
// Collection for: cyphers
const cyphers = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/cyphers',
  })
});
// Collection for: descriptors
const descriptors = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/descriptors',
  })
});
// Collection for: equipment
const equipment = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/equipment',
  })
});
// Collection for: flavors
const flavors = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/flavors',
  })
});
// Collection for: foci
const foci = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/foci',
  })
});
// Collection for: rituals
const rituals = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/rituals',
  })
});
// Collection for: rules
const rules = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/rules',
  })
});
// Collection for: skill-lists
const skilllists = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/skill-lists',
  })
});
// Collection for: stats
const stats = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/stats',
  })
});
// Collection for: tables
const tables = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/tables',
  })
});
// Collection for: types
const types = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/csrd/en/types',
  })
});

// Export all the generated collections for Astro.
export const collections = {
  abilities,
  artifacts,
  cantrips,
  characterarcs,
  characteroptions,
  creaturesnpcs,
  cyphershortsscenarios,
  cyphers,
  descriptors,
  equipment,
  flavors,
  foci,
  rituals,
  rules,
  skilllists,
  stats,
  tables,
  types,
};

