import { glob } from 'astro/loaders';
import { defineCollection, z } from "astro:content";

// This file is auto-generated by the 'generate-collections.mjs' script. Do not edit manually.
// Generated on: 2025-07-13T22:46:08.111Z

// A generic base schema that allows for common fields and any other fields.
// This provides flexibility while ensuring core fields like 'title' are present.
const baseSchema = z.object({
    title: z.string(),
    aliases: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    collection: z.string().optional(),
    kind: z.string().optional(),
  }).passthrough(); // .passthrough() allows any other fields without validation.


// Collection for: abilities
const abilities = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/abilities',
  })
});
// Collection for: artifacts
const artifacts = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/artifacts',
  })
});
// Collection for: cantrips
const cantrips = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/cantrips',
  })
});
// Collection for: character-arcs
const characterarcs = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/character-arcs',
  })
});
// Collection for: character-options
const characteroptions = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/character-options',
  })
});
// Collection for: creatures-npcs
const creaturesnpcs = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/creatures-npcs',
  })
});
// Collection for: cypher-shorts-scenarios
const cyphershortsscenarios = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/cypher-shorts-scenarios',
  })
});
// Collection for: cyphers
const cyphers = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/cyphers',
  })
});
// Collection for: descriptors
const descriptors = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/descriptors',
  })
});
// Collection for: equipment
const equipment = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/equipment',
  })
});
// Collection for: flavors
const flavors = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/flavors',
  })
});
// Collection for: foci
const foci = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/foci',
  })
});
// Collection for: rituals
const rituals = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/rituals',
  })
});
// Collection for: rules
const rules = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/rules',
  })
});
// Collection for: skill-lists
const skilllists = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/skill-lists',
  })
});
// Collection for: stats
const stats = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/stats',
  })
});
// Collection for: tables
const tables = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/tables',
  })
});
// Collection for: types
const types = defineCollection({
  schema: baseSchema,
  loader: glob({
    pattern: '**/*.{md,mdx}',
    base: 'src/content/compendiums/CSRD/en/types',
  })
});

// Export all the generated collections for Astro.
export const collections = {
  abilities,
  artifacts,
  cantrips,
  characterarcs,
  characteroptions,
  creaturesnpcs,
  cyphershortsscenarios,
  cyphers,
  descriptors,
  equipment,
  flavors,
  foci,
  rituals,
  rules,
  skilllists,
  stats,
  tables,
  types,
};

