// This file is auto-generated by the 'generate-collections.mjs' script. Do not edit manually.
// Generated on: 2025-07-12T15:03:26.823Z

import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

// A generic base schema that allows for common fields and any other fields.
// This provides flexibility while ensuring core fields like 'title' are present.
const baseSchema = z.object({
    title: z.string(),
    aliases: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    collection: z.string().optional(),
    kind: z.string().optional(),
  }).passthrough(); // .passthrough() allows any other fields without validation.


// Collection for: Abilities
const abilities = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Abilities' }),
  schema: baseSchema,
});
// Collection for: Artifacts
const artifacts = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Artifacts' }),
  schema: baseSchema,
});
// Collection for: Cantrips
const cantrips = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Cantrips' }),
  schema: baseSchema,
});
// Collection for: CharacterArcs
const characterarcs = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/CharacterArcs' }),
  schema: baseSchema,
});
// Collection for: CharacterOptions
const characteroptions = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/CharacterOptions' }),
  schema: baseSchema,
});
// Collection for: CreaturesNPCs
const creaturesnpcs = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/CreaturesNPCs' }),
  schema: baseSchema,
});
// Collection for: Cyphers
const cyphers = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Cyphers' }),
  schema: baseSchema,
});
// Collection for: CypherShortsScenarios
const cyphershortsscenarios = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/CypherShortsScenarios' }),
  schema: baseSchema,
});
// Collection for: Descriptors
const descriptors = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Descriptors' }),
  schema: baseSchema,
});
// Collection for: Equipment
const equipment = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Equipment' }),
  schema: baseSchema,
});
// Collection for: Flavors
const flavors = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Flavors' }),
  schema: baseSchema,
});
// Collection for: Foci
const foci = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Foci' }),
  schema: baseSchema,
});
// Collection for: Rituals
const rituals = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Rituals' }),
  schema: baseSchema,
});
// Collection for: Rules
const rules = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Rules' }),
  schema: baseSchema,
});
// Collection for: SkillLists
const skilllists = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/SkillLists' }),
  schema: baseSchema,
});
// Collection for: Stats
const stats = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Stats' }),
  schema: baseSchema,
});
// Collection for: Tables
const tables = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Tables' }),
  schema: baseSchema,
});
// Collection for: Types
const types = defineCollection({
  loader: glob({ pattern: '**/[^_]*', base: './src/content/compendiums/CSRD/en/Types' }),
  schema: baseSchema,
});

// Export all the generated collections for Astro.
export const collections = {
  abilities,
  artifacts,
  cantrips,
  characterarcs,
  characteroptions,
  creaturesnpcs,
  cyphers,
  cyphershortsscenarios,
  descriptors,
  equipment,
  flavors,
  foci,
  rituals,
  rules,
  skilllists,
  stats,
  tables,
  types,
};
